version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 135790135790
      POSTGRES_DB: nest
    networks:
      - firstnest
networks:
  firstnest: